name: Trigger auto deployment for terra-major-webapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/terra-major-webapp-AutoDeployTrigger-0e634060-4a71-407b-8327-c0d3ced8ce2f.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.TERRAMAJORWEBAPP_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: terramajor.azurecr.io
          registryUsername: ${{ secrets.TERRAMAJORWEBAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TERRAMAJORWEBAPP_REGISTRY_PASSWORD }}
          containerAppName: terra-major-webapp
          resourceGroup: terra-major-non-prod
          imageToBuild: terramajor.azurecr.io/terra-major-webapp:${{ github.sha }}
          

     

